### ISSUE TITLE
[BUG] type:null causes error when used with anyOf

### ISSUE THREAD

**Issue by dskvr** [quicktype/quicktype#1170]
Case:
```yaml
someValue: 
  anyOf:
    - type: null
    - type: string 
```
Results in following error:

```bash
Error: Cannot read property 'toString' of null.
```
This means that otherwise valid schemas cannot be generated. 
https://json-schema.org/understanding-json-schema/reference/null.html
